all:
  children:
    cisco_ios:
      hosts:
        Router: { ansible_host: 192.168.1.2 }
        SW2: { ansible_host: 192.168.1.11 }
        SW3: { ansible_host: 192.168.1.12 }
        SW1: { ansible_host: 192.168.1.13 }
        AP: { ansible_host: 192.168.1.14 }
        AC: { ansible_host: 192.168.1.15 }
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
    firewall:
      hosts:
        FW01: { ansible_host: 192.168.1.10 }
      vars:
        ansible_connection: network_cli
        ansible_network_os: asa
  vars:
    ansible_user: ansible
    ansible_password: ANSIBLE_PASS
    ansible_become: yes
    ansible_become_method: enable
