---
- name: 02 – Configure management IPs on IOS devices
  hosts: cisco_ios
  gather_facts: no

  vars:
    mgmt_ips:
      Router: "192.168.1.2"
      SW2: "192.168.1.11"
      SW3: "192.168.1.12"
      SW1: "192.168.1.13"
      AP: "192.168.1.14"
      AC: "192.168.1.15"

    mgmt_interfaces:
      Router: "interface GigabitEthernet0/0"
      SW2: "interface Vlan1"
      SW3: "interface Vlan1"
      SW1: "interface Vlan1"
      AP: "interface GigabitEthernet0"
      AC: "interface GigabitEthernet0"

  tasks:
    - name: Configure management interface & IP on IOS devices
      ios_config:
        lines:
          - "{{ mgmt_interfaces[inventory_hostname] }}"
          - "ip address {{ mgmt_ips[inventory_hostname] }} 255.255.255.0"
          - no shutdown
        # after interface stanza
        parents: "{{ mgmt_interfaces[inventory_hostname] | regex_replace('^interface ', '') }}"
      when: inventory_hostname in mgmt_ips.keys()

- name: 02 – Configure management interface on ASA firewall
  hosts: firewall
  gather_facts: no

  tasks:
    - name: Configure ASA Management0/0
      asa_config:
        lines:
          - interface Management0/0
          - nameif mgmt
          - security-level 100
          - ip address 192.168.1.10 255.255.255.0
          - no shutdown
