---
- name: 07 – Install & configure Snort 3 IDS/IPS on Ubuntu controller
  hosts: localhost
  connection: local
  become: yes
  vars_prompt:
    - name: ansible_become_pass
      prompt: "Enter sudo password"
      private: yes

  vars:
    # where to keep sources and where to install Snort
    src_root: /usr/local/src/snort_src
    install_prefix: /usr/local/snort3
    daq_repo: https://github.com/snort3/libdaq.git
    snort_repo: https://github.com/snort3/snort3.git

  tasks:
    - name: Install Snort 3 build dependencies
      apt:
        name:
          - build-essential
          - autotools-dev
          - libdumbnet-dev
          - libluajit-5.1-dev
          - libpcap-dev
          - zlib1g-dev
          - pkg-config
          - libhwloc-dev
          - cmake
          - libtool
          - git
          - autoconf
          - bison
          - flex
          - libnetfilter-queue-dev
          - libmnl-dev
        state: present
        update_cache: yes

    - name: Create source directory
      file:
        path: "{{ src_root }}"
        state: directory
        mode: '0755'

    - name: Clone DAQ library
      git:
        repo: "{{ daq_repo }}"
        dest: "{{ src_root }}/libdaq"
        depth: 1

    - name: Build & install DAQ
      shell: |
        cd {{ src_root }}/libdaq
        ./bootstrap
        ./configure
        make
        make install
      args:
        creates: /usr/local/lib/libdaq.so

    - name: Clone Snort 3
      git:
        repo: "{{ snort_repo }}"
        dest: "{{ src_root }}/snort3"
        depth: 1

    - name: Build & install Snort 3
      shell: |
        cd {{ src_root }}/snort3
        ./configure_cmake.sh --prefix={{ install_prefix }} --enable-tcmalloc
        cd build
        make -j "$(nproc)"
        make install
      args:
        creates: "{{ install_prefix }}/bin/snort"

    - name: Update shared‐library cache
      shell: ldconfig

